 spring:
    data:
        mongodb:
            host: ds044587.mlab.com
            port: 44587
            database: usuarios
            username: arsw
            password: arsw1
    redis:
       host: 34.212.138.202
       port: 6379